matrix:
  PERL_VERSIONS:
    - 5.36
    - 5.38
  THREADS:
    - ""
    - "-threaded"

steps:
  test:
    image: "quay.io/simcop2387/perl-debug-containers:${PERL_VERSIONS}-main${THREADS}-bookworm-backports"
    commands:
      - apt update && apt install -y libssl-dev git
      - cpanm --verbose Dist::Zilla
      - dzil authordeps | xargs cpanm --verbose 
      - cpanm --notest --verbose IO::Async
      - dzil listdeps | xargs cpanm --verbose
      - dzil test