matrix:
  PERL_VERSION:
    - 5.36
    - 5.38
  THREADS:
    - ""
    - "-threaded"

depends_on: 
  - build-test-images

steps:
  test:
      image: "gitea.simcop2387.info/simcop2387/openai-async-test-images:perl-${PERL_VERSION}${THREADS}"
      commands:
        - dzil authordeps --missing | xargs cpanm
        - dzil listdeps --missing | xargs cpanm
        - dzil test